### ISSUE TITLE
atomix-agent usage from master (e105b428bd45b42ed92f28cffde5ccbee86af6fd) fails

### ISSUE THREAD

**Issue by khmarbaise** [atomix/atomix#562] opened 2018-05-17 15:25 UTC
Currently trying to use the `atomix-agent` and trying to start the example given in the [documentation](http://atomix.io/docs/latest/getting-started/) and created the given `atomix.yaml` file which unfortunately results in the following error:
```
~/ws-git-xxx/atomix (master)$ /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -jar agent/target/atomix-agent.jar --config atomix.yaml node1
Exception in thread "main" io.atomix.utils.config.ConfigurationException: Failed to parse YAML file
	at io.atomix.core.config.jackson.JacksonConfigProvider.loadYaml(JacksonConfigProvider.java:100)
	at io.atomix.core.config.jackson.JacksonConfigProvider.load(JacksonConfigProvider.java:86)
	at io.atomix.utils.config.Configs.load(Configs.java:58)
	at io.atomix.agent.AtomixAgent.loadConfig(AtomixAgent.java:211)
	at io.atomix.agent.AtomixAgent.main(AtomixAgent.java:132)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "nodes" (class io.atomix.cluster.ClusterConfig), not marked as ignorable (7 known properties: "membership", "members", "name", "local-member-id", "multicast-address", "local-member", "multicast-enabled"])
 at [Source: (File); line: 3, column: 5] (through reference chain: io.atomix.core.AtomixConfig["cluster"]->io.atomix.cluster.ClusterConfig["nodes"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at io.atomix.core.config.jackson.JacksonConfigProvider.loadYaml(JacksonConfigProvider.java:98)
	... 4 more
```

**Comment by khmarbaise** [comment] 2018-05-18 08:37
After dived more into the details I found out that the configuration given on the [documentation page](http://atomix.io/docs/latest/getting-started/) is not correct. If I change the configuration `atomix.yaml` to the following:
```yaml
cluster:
  name: FirstCluster
  members:
    node1:
      type: persistent
      address: localhost:20001
    node2:
      type: persistent
      address: localhost:20002
    node3:
      type: persistent
      address: localhost:20003
```
it results into startup messages...after another tweak which results in this configuration file
```yaml
cluster:
  name: FirstCluster
  members:
    node1:
      type: persistent
      address: localhost:20001
    node2:
      type: persistent
      address: localhost:20002
    node3:
      type: persistent
      address: localhost:20003
# A list of partition groups
partition-groups:
  raft:
    type: raft
    storage-level: memory
    partitions: 7
    partition-size: 3
    data-directory: target/test-logs/core
    members:
      - node1
      - node2
      - node3
profiles:
  - consensus
  - data-grid
```
It looks like nodes are stating up..But I get exceptions about bind address already in use like this:

```
10:32:50.908 [raft-server-raft-partition-1] INFO  i.a.p.raft.impl.DefaultRaftServer - RaftServer{raft-partition-1} - Server started successfully!
10:32:50.908 [raft-server-raft-partition-1] INFO  i.a.p.r.p.impl.RaftPartitionServer - Successfully started server for partition PartitionId{id=1, group=raft}
10:32:50.909 [raft-client-raft-partition-1-0] INFO  i.a.p.r.p.impl.RaftPartitionClient - Successfully started client for partition PartitionId{id=1, group=raft}
10:32:50.914 [raft-server-raft-partition-2] INFO  i.a.p.r.c.impl.RaftClusterContext - RaftServer{raft-partition-2} - Successfully joined via node2
10:32:50.914 [raft-server-raft-partition-2] INFO  i.a.p.raft.impl.DefaultRaftServer - RaftServer{raft-partition-2} - Server started successfully!
10:32:50.914 [raft-server-raft-partition-2] INFO  i.a.p.r.p.impl.RaftPartitionServer - Successfully started server for partition PartitionId{id=2, group=raft}
10:32:50.916 [raft-client-raft-partition-2-0] INFO  i.a.p.r.p.impl.RaftPartitionClient - Successfully started client for partition PartitionId{id=2, group=raft}
10:32:50.916 [raft-client-raft-partition-2-0] INFO  i.a.p.r.partition.RaftPartitionGroup - Started
10:32:50.916 [raft-client-raft-partition-2-0] INFO  i.a.p.p.impl.DefaultPartitionService - Started
10:32:50.979 [raft-client-system-partition-1-7] INFO  i.a.core.impl.CoreTransactionService - Started
10:32:50.979 [raft-client-system-partition-1-7] INFO  i.a.core.impl.CorePrimitivesService - Started
10:32:50.979 [atomix-cluster-0] INFO  io.atomix.cluster.AtomixCluster - Started
10:32:50.982 [main] INFO  io.atomix.agent.AtomixAgent - Atomix listening at localhost:20001
10:32:51.505 [netty-messaging-event-nio-client-9] WARN  i.a.c.i.DefaultPersistentMetadataService - Anti-entropy advertisement to localhost:20003 failed!
Exception in thread "main" java.util.concurrent.CompletionException: java.net.BindException: Address already in use
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at io.atomix.agent.AtomixAgent.main(AtomixAgent.java:194)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:380)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:355)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
10:32:52.508 [netty-messaging-event-nio-client-3] WARN  i.a.c.i.DefaultPersistentMetadataService - Anti-entropy advertisement to localhost:20003 failed!
10:32:56.515 [netty-messaging-event-nio-client-12] W
```

**Comment by johnou** [comment] 2018-06-19 06:44
Duplicate of https://github.com/atomix/atomix/issues/570

**Closed by johnou** 2018-06-19 06:44 UTC
