### ISSUE TITLE
snapshotting logic in ResourceStateMachine

### ISSUE THREAD

**Issue by madjam** [atomix/atomix#129] opened 2016-02-20 03:57 UTC
I noticed the following exception after restarting a node.

```
2016-02-19 19:40:46,656 | WARN  | artition-0-state | ServerStateMachineExecutor      | Operation InstanceCommand[resource=474, command=ResourceCommand[command=io.atomix.variables.state.LongCommands$IncrementAndGet@10a8c8e4, consistency=LINEARIZABLE], consistency=LINEARIZABLE] failed
io.atomix.manager.state.ResourceManagerException: unknown resource: 474
	at io.atomix.manager.state.ResourceManagerState.operateResource(ResourceManagerState.java:99)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.manager.state.ResourceManagerState$$Lambda$52/853973916.apply(Unknown Source)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.ServerStateMachineExecutor.executeOperation(ServerStateMachineExecutor.java:143)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.ServerStateMachine.executeCommand(ServerStateMachine.java:925)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
	at io.atomix.copycat.server.state.ServerStateMachine.lambda$apply$29(ServerStateMachine.java:839)[68:org.onosproject.onlab-thirdparty:1.5.0.SNAPSHOT]
```
the key thing is this exception only occurs after a snapshot is taken. If no snapshots were taken you don't see this error.

In `ResourceManagerState`, the snapshot logic is to merely take snapshots of the resource state machines. But `ResourceManagerState` itself has some state that probably needs to be included in the snaphot.

**Comment by kuujo** [comment] 2016-02-20 04:23
Actually, this may be a similar issue to one that I fixed with sessions in
Copycat a while back. Let me investigate this a bit...

**Comment by madjam** [comment] 2016-02-20 04:40
Since a state machine can be `Snapshottable` and also employ log cleaning this should not be an issue. The local state in `ResourceStateManager` should have simply been retained in the log and when the log is replayed the state reconstructed. @kuujo: is my understanding correct?

**Comment by kuujo** [comment] 2016-02-20 05:18
@madjam that's right. The commit that created a resource is held open until the resource is deleted:
https://github.com/atomix/atomix/blob/master/manager/src/main/java/io/atomix/manager/state/ResourceManagerState.java#L253

Thus, as long as the resource is not deleted, that commit should always be in the log and so a replay of the log should result in the resource being created.

I haven't been able to reproduce this, but I think I see what the problem is. I'll have a fix for it momentito...

**Closed** 2016-02-20 08:34 UTC
Labels: bug
