### ISSUE TITLE
BlockingDistributedLock throws 100% of the time in some scenarios

### ISSUE THREAD

**Issue by rroller** [atomix/atomix#544] opened 2018-05-06 04:08 UTC
On my laptop, I can reproduce the error below by doing the follow - I’m using the latest 2.1.0-SNAPSHOT version

1. Start atomix with 4 PERSISTENT nodes as follows...
```java
        final Atomix atomix = Atomix.builder()
                .withManagementGroup((RaftPartitionGroup.builder("system")
                        .withNumPartitions(1)
                        .withMembers(members.stream().toArray(Member[]::new))
                        .withDataDirectory(dataDir)
                        .build()))
                .withPartitionGroups(RaftPartitionGroup.builder("raft")
                        .withNumPartitions(1)
                        .withMembers(members.stream().toArray(Member[]::new))
                        .withDataDirectory(dataDir)
                        .build())
                .withMembers(members.stream().toArray(Member[]::new))
                .withLocalMember(local)
                .withClusterName("Cluster name")
                .build()
```

2. Take 1 node down
3. Take 1 more node down (now we have 2 nodes ups out of 4)
4. Start one of the previously downed nodes
5. Any node attempting to take a lock will get the following exception

```
io.atomix.primitive.PrimitiveException$Timeout: null
        at io.atomix.core.lock.impl.BlockingDistributedLock.complete(BlockingDistributedLock.java:77)
        at io.atomix.core.lock.impl.BlockingDistributedLock.tryLock(BlockingDistributedLock.java:57)
        at com.example.runOneIteration(xScheduler.java:55)
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:193)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rroller** [comment] 2018-05-07 05:13
Why different names? That’s the purpose of the lock, to take a single lock across a fleet such that a single host “wins” and takes the lock blocking the others. 

When 2 of the 4 nodes are down we don’t have quram so what would retrying do?

**Comment by rroller** [comment] 2018-05-07 05:29
Those locks don’t timeout though. They are meant to block until the lock is obtained — which is what I see until I lose quram. And also, how do you know the unlock failed?

**Comment by tanbangcheng** [comment] 2018-05-07 08:15
this is a bug,
1. lock 0 locked others(1,2,3) enqueue, now the `queue` of `DefaultDistributedLockService` has 3 request [1,2,3]
2. lock 0 unlock, lock 1 locked, and the `queue` is [2,3], lockHolder is lock 1
3. server 2 and 3 down
4. 500ms later, lock 1 `unlock`, and `unlcok` throw `RejectedExecutionException`, `unlock` failed
5. `DEFAULT_OPERATION_TIMEOUT_MILLIS`(5s) later,  lock 2 and lock 3 timeout, invoke `unlock` in `finally`, but the `private final AtomicInteger lock = new AtomicInteger();` in `DistributedLockProxy` is 0, `unlock` not send UNLOCK command to Server.

**Comment by rroller** [comment] 2018-05-07 09:58
A bug in Atomix?

**Comment by tanbangcheng** [comment] 2018-05-07 11:58
the problem is server 2 and 3 down, but `onClose` and `releaseSession` not invoked,  so that the lock
 locked by server 2 or 3 not released, sorry my last comment is wrong, deleted

**Comment by tanbangcheng** [comment] 2018-05-07 14:08
currently, closing partition does not close proxies at the same time,  default session timeout is 30s, 
before fixed this, you can retry `lock`  during this time, until session of server 2 and 3 expired and release lock, and set a shorter duration like this,
```JAVA
MultiRaftProtocol.builder()
                      .withMaxRetries(5)
                      .withMaxTimeout(Duration.ofMillis(1000))
                      .build()
```

**Comment by rroller** [comment] 2018-05-07 14:25
Using `.withMaxTimeout(Duration.ofMillis(1000))` worked.

**Comment by kuujo** [comment] 2018-05-07 21:01
So, I spent a lot of time working with this test, and there are a few things going on here.

First, what happens in Raft when a node is killed (or shutdown) is the leader will normally react to the `MEMBER_DEACTIVATED` event and expire any primitive sessions owned by the node. If the leader for some reason can’t expire the sessions, they’ll eventually be expired once their timeout has passed. The timeout is based on the log time and thus requires Raft to make progress to expire sessions. The lock service releases locks held by a node when the associated session expires or is closed.

So, there are a few issues here. First, what’s happening when 2/4 nodes are shutdown is the Raft partition loses availability. That prevents the leader from expiring the sessions associated with the second node shutdown. That’s fine since it will fallback to the session timeout, but that timeout takes significantly longer than the timers specified in this test. Once a node is restarted and a leader for the Raft partition is elected again, the cluster has to make progress for 30 deterministic seconds before those sessions will be expired. Furthermore, because of the threads locking/unlocking their locks, there are several lock requests in the queue and it takes additional time to grant and unlock them.

The second problem is during that time, some of the lock attempts in the background threads timeout. But after a lock attempt is timed out by the synchronous API, it may actually succeed, and there’s nothing that will release the lock if it does. So, this is a bug. The synchronous lock probably needs to eschew timeouts and rely only on the asynchronous proxy implementation for timing out locks to ensure they’re properly cleaned up. In the asynchronous implementation, we can listen for state changes in the primitive client to ensure locks are released if a lock attempt fails.

Anyways, adjusting some of the timeouts makes this test pass, but we need to adjust the defaults and fix the synchronous lock API.

**Comment by rroller** [comment] 2018-05-08 04:04
Thanks for the deep dive. If we tweak the timeout are we still at risk for putting our self in a non-recoverable scenario? Or should we just wait for a bug fix?

**Comment by kuujo** [comment] 2018-05-09 17:47
The bug fix is above. I never like relying on timeouts for safety, especially considering these timeouts are based on the Raft log which can lag an unbounded amount of time behind real time.

**Closed** 2018-05-09 22:12 UTC
